spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/orderdb
      auto-index-creation: true

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb: DEBUG
